// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$59 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$59() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ripoffline",
        constants$16.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "savetty",
        constants$18.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "scanw",
        constants$7.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "scr_dump",
        constants$7.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "scr_init",
        constants$7.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "scrl",
        constants$19.const$3
    );
}


