// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$82 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$82() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "curses_version",
        constants$10.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "define_key",
        constants$27.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "extended_color_content",
        constants$82.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "extended_pair_content",
        constants$16.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "extended_slk_color",
        constants$19.const$3
    );
}


