// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$75 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$75() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "winsertln",
        constants$7.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "winsnstr",
        constants$6.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "winsstr",
        constants$9.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "winstr",
        constants$9.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "wmove",
        constants$31.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "wnoutrefresh",
        constants$7.const$2
    );
}


