// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$101 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$101() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "slk_attr_set_sp",
        constants$70.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "slk_clear_sp",
        constants$7.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_SHORT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "slk_color_sp",
        constants$101.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "slk_init_sp",
        constants$27.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "slk_label_sp",
        constants$95.const$3
    );
}


