// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$116 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$116() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "_tracechar",
        constants$43.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "_tracechtype",
        constants$43.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "_tracechtype2",
        constants$53.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "trace",
        constants$30.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "curses_trace",
        constants$19.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "exit_curses",
        constants$30.const$3
    );
}


