// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final VarHandle const$0 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_mode"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(cookie_read_function_t.class, "apply", constants$6.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$6.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(cookie_write_function_t.class, "apply", constants$6.const$1);
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
}


