// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$77 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$77() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "wstandout",
        constants$7.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "wstandend",
        constants$7.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "wsyncdown",
        constants$14.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "wsyncup",
        constants$14.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "wtimeout",
        constants$70.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "wtouchln",
        constants$49.const$1
    );
}


