// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$79 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$79() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "tiparm",
        constants$10.const$3
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "tiparm_s",
        constants$79.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "tiscan_s",
        constants$14.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getattrs",
        constants$7.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getcurx",
        constants$7.const$2
    );
}


