// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$92 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$92() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "delay_output_sp",
        constants$27.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "doupdate_sp",
        constants$7.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "echo_sp",
        constants$7.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "endwin_sp",
        constants$7.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_BYTE,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "erasechar_sp",
        constants$92.const$4
    );
}


