// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(cookie_seek_function_t.class, "apply", constants$6.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$6.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(cookie_close_function_t.class, "apply", constants$7.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$7.const$2
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("read"),
        RuntimeHelper.POINTER.withName("write"),
        RuntimeHelper.POINTER.withName("seek"),
        RuntimeHelper.POINTER.withName("close")
    ).withName("_IO_cookie_io_functions_t");
}


