// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$85 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$85() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "keybound",
        constants$53.const$5
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "keyok",
        constants$85.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nofilter",
        constants$36.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "reset_color_pairs",
        constants$36.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "resize_term",
        constants$38.const$5
    );
}


