// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3() {}
    static final VarHandle const$0 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_IO_buf_end"));
    static final VarHandle const$1 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_IO_save_base"));
    static final VarHandle const$2 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_IO_backup_base"));
    static final VarHandle const$3 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_IO_save_end"));
    static final VarHandle const$4 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_markers"));
    static final VarHandle const$5 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_chain"));
}


