// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$76 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$76() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "wprintw",
        constants$9.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "wredrawln",
        constants$31.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "wrefresh",
        constants$7.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandleVariadic(
        "wscanw",
        constants$9.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "wscrl",
        constants$27.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "wsetscrreg",
        constants$31.const$0
    );
}


