// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mvinsch",
        constants$44.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mvinsnstr",
        constants$44.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mvinsstr",
        constants$45.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mvinstr",
        constants$45.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandleVariadic(
        "mvprintw",
        constants$45.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandleVariadic(
        "mvscanw",
        constants$45.const$0
    );
}


