// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$74 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$74() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "winch",
        constants$7.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "winchnstr",
        constants$6.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "winchstr",
        constants$9.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "winnstr",
        constants$6.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "winsch",
        constants$27.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "winsdelln",
        constants$27.const$2
    );
}


