// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "funlockfile",
        constants$14.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "__uflow",
        constants$7.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "__overflow",
        constants$27.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(NCURSES_OUTC.class, "apply", constants$19.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$19.const$3
    );
}


