// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mvcur",
        constants$46.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mvdelch",
        constants$38.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mvderwin",
        constants$31.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mvgetch",
        constants$38.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mvgetnstr",
        constants$44.const$4
    );
}


