// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "noecho",
        constants$18.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "nonl",
        constants$18.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "noqiflush",
        constants$36.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "noraw",
        constants$18.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "notimeout",
        constants$32.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "overlay",
        constants$9.const$3
    );
}


