// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "flash",
        constants$18.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "flushinp",
        constants$18.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getbkgd",
        constants$7.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getch",
        constants$18.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getnstr",
        constants$27.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getstr",
        constants$7.const$2
    );
}


