// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$84 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$84() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "is_echo",
        constants$18.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "is_nl",
        constants$18.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "is_raw",
        constants$18.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_BOOLEAN,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "is_term_resized",
        constants$84.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "key_defined",
        constants$7.const$2
    );
}


