// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$86 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$86() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "resizeterm",
        constants$38.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "set_escdelay",
        constants$19.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "set_tabsize",
        constants$19.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "use_default_colors",
        constants$18.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "use_legacy_coding",
        constants$19.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "use_screen",
        constants$14.const$5
    );
}


