// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$117 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$117() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "unctrl",
        constants$43.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "unctrl_sp",
        constants$95.const$3
    );
    static final MemorySegment const$2 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("6.4");
    static final MemorySegment const$3 = MemorySegment.ofAddress(0L);
    static final MemorySegment const$4 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("/tmp");
}


