// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$109 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$109() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "set_escdelay_sp",
        constants$27.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "set_tabsize_sp",
        constants$27.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "use_default_colors_sp",
        constants$7.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "use_legacy_coding_sp",
        constants$27.const$2
    );
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("curscr", RuntimeHelper.POINTER);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("newscr", RuntimeHelper.POINTER);
}


