// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$47 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$47() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mvgetstr",
        constants$45.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mvhline",
        constants$46.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mvinch",
        constants$38.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mvinchnstr",
        constants$44.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mvinchstr",
        constants$45.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mvinnstr",
        constants$44.const$4
    );
}


