// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$99 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$99() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "reset_shell_mode_sp",
        constants$7.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "resetty_sp",
        constants$7.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(ripoffline_sp$x0.class, "apply", constants$27.const$2);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ripoffline_sp",
        constants$69.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "savetty_sp",
        constants$7.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "scr_init_sp",
        constants$9.const$3
    );
}


