// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$106 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$106() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "free_pair_sp",
        constants$27.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "get_escdelay_sp",
        constants$7.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "init_extended_color_sp",
        constants$51.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "init_extended_pair_sp",
        constants$49.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "is_cbreak_sp",
        constants$7.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "is_echo_sp",
        constants$7.const$2
    );
}


