// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$65 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$65() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "termattrs",
        constants$18.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "termname",
        constants$10.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "timeout",
        constants$30.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "touchline",
        constants$31.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "touchwin",
        constants$7.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "typeahead",
        constants$19.const$3
    );
}


