// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$87 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$87() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "use_window",
        constants$14.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "wresize",
        constants$31.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "use_extended_names",
        constants$87.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "wgetparent",
        constants$10.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "is_cleared",
        constants$42.const$5
    );
}


