// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$18 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$18() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fgetc",
        constants$7.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getc",
        constants$7.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getchar",
        constants$18.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getc_unlocked",
        constants$7.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getchar_unlocked",
        constants$18.const$2
    );
}


