// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$100 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$100() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "scr_restore_sp",
        constants$9.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "scr_set_sp",
        constants$9.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "slk_attroff_sp",
        constants$27.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "slk_attron_sp",
        constants$27.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "slk_attrset_sp",
        constants$27.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "slk_attr_sp",
        constants$7.const$2
    );
}


