// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$94 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$94() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "has_ic_sp",
        constants$42.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "has_il_sp",
        constants$42.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_SHORT,
        JAVA_SHORT,
        JAVA_SHORT,
        JAVA_SHORT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "init_color_sp",
        constants$94.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_SHORT,
        JAVA_SHORT,
        JAVA_SHORT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "init_pair_sp",
        constants$94.const$4
    );
}


