// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$88 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$88() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "is_idcok",
        constants$42.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "is_idlok",
        constants$42.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "is_immedok",
        constants$42.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "is_keypad",
        constants$42.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "is_leaveok",
        constants$42.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "is_nodelay",
        constants$42.const$5
    );
}


