// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$57 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$57() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "prefresh",
        constants$56.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandleVariadic(
        "printw",
        constants$7.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "putwin",
        constants$9.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "qiflush",
        constants$36.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "raw",
        constants$18.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "redrawwin",
        constants$7.const$2
    );
}


