// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "idcok",
        constants$39.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "idlok",
        constants$32.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "immedok",
        constants$39.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "inch",
        constants$18.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "inchnstr",
        constants$27.const$2
    );
}


