// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$110 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$110() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("stdscr", RuntimeHelper.POINTER);
    static final VarHandle const$1 = JAVA_INT.varHandle();
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("COLORS", JAVA_INT);
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("COLOR_PAIRS", JAVA_INT);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("COLS", JAVA_INT);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("ESCDELAY", JAVA_INT);
}


