// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "keyname",
        constants$43.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "keypad",
        constants$32.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "killchar",
        constants$36.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "leaveok",
        constants$32.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "longname",
        constants$10.const$1
    );
}


