// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$26 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$26() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fileno_unlocked",
        constants$7.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "pclose",
        constants$7.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "popen",
        constants$11.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ctermid",
        constants$10.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "flockfile",
        constants$14.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ftrylockfile",
        constants$7.const$2
    );
}


