// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$112 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$112() {}
    static final VarHandle const$0 = constants$111.const$2.varHandle(MemoryLayout.PathElement.groupElement("z"));
    static final VarHandle const$1 = constants$111.const$2.varHandle(MemoryLayout.PathElement.groupElement("bstate"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "has_mouse",
        constants$31.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getmouse",
        constants$7.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ungetmouse",
        constants$7.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mousemask",
        constants$16.const$5
    );
}


