// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$81 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$81() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getpary",
        constants$7.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(NCURSES_WINDOW_CB.class, "apply", constants$9.const$3);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$9.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(NCURSES_SCREEN_CB.class, "apply", constants$9.const$3);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "alloc_pair",
        constants$38.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "assume_default_colors",
        constants$38.const$5
    );
}


