// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$54 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$54() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "newterm",
        constants$11.const$5
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "newwin",
        constants$54.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nl",
        constants$18.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "nocbreak",
        constants$18.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "nodelay",
        constants$32.const$1
    );
}


