// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$89 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$89() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "is_notimeout",
        constants$42.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "is_pad",
        constants$42.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "is_scrollok",
        constants$42.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "is_subwin",
        constants$42.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "is_syncok",
        constants$42.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "wgetdelay",
        constants$7.const$2
    );
}


