// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$96 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$96() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "longname_sp",
        constants$10.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mvcur_sp",
        constants$51.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "napms_sp",
        constants$27.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "newpad_sp",
        constants$96.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "newterm_sp",
        constants$96.const$5
    );
}


