// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$66 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$66() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ungetch",
        constants$19.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "untouchwin",
        constants$7.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        JAVA_BOOLEAN
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "use_env",
        constants$66.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "use_tioctl",
        constants$66.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vidattr",
        constants$19.const$3
    );
}


