// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$60 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$60() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "scroll",
        constants$7.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "scrollok",
        constants$32.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "scr_restore",
        constants$7.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "scr_set",
        constants$7.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "setscrreg",
        constants$38.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "set_term",
        constants$10.const$3
    );
}


