// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vasprintf",
        constants$14.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandleVariadic(
        "__asprintf",
        constants$9.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "asprintf",
        constants$9.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vdprintf",
        constants$16.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandleVariadic(
        "dprintf",
        constants$16.const$5
    );
}


