// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$104 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$104() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "use_tioctl_sp",
        constants$39.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vidattr_sp",
        constants$27.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vidputs_sp",
        constants$69.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "alloc_pair_sp",
        constants$31.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "assume_default_colors_sp",
        constants$31.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "define_key_sp",
        constants$6.const$5
    );
}


