// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$83 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$83() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "find_pair",
        constants$38.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "free_pair",
        constants$19.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "get_escdelay",
        constants$18.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "init_extended_color",
        constants$46.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "init_extended_pair",
        constants$44.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "is_cbreak",
        constants$18.const$2
    );
}


