// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$36 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$36() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "echochar",
        constants$19.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "erase",
        constants$18.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "endwin",
        constants$18.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_BYTE);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "erasechar",
        constants$36.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "filter",
        constants$36.const$5
    );
}


