// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$115 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$115() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "has_key",
        constants$19.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "has_key_sp",
        constants$27.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mcprint_sp",
        constants$6.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandleVariadic(
        "_tracef",
        constants$14.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "_traceattr",
        constants$43.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "_traceattr2",
        constants$53.const$5
    );
}


