// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$67 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$67() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vidputs",
        constants$16.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vline",
        constants$38.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vwprintw",
        constants$14.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "vw_printw",
        constants$14.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vwscanw",
        constants$14.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vw_scanw",
        constants$14.const$5
    );
}


