// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$68 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$68() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "waddch",
        constants$27.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "waddchnstr",
        constants$6.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "waddchstr",
        constants$9.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "waddnstr",
        constants$6.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "waddstr",
        constants$9.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "wattron",
        constants$27.const$2
    );
}


