// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(2, JAVA_INT).withName("__val")
    ).withName("");
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("__count"),
        MemoryLayout.unionLayout(
            JAVA_INT.withName("__wch"),
            MemoryLayout.sequenceLayout(4, JAVA_BYTE).withName("__wchb")
        ).withName("__value")
    ).withName("");
    static final VarHandle const$2 = constants$0.const$1.varHandle(MemoryLayout.PathElement.groupElement("__count"));
    static final UnionLayout const$3 = MemoryLayout.unionLayout(
        JAVA_INT.withName("__wch"),
        MemoryLayout.sequenceLayout(4, JAVA_BYTE).withName("__wchb")
    ).withName("");
    static final VarHandle const$4 = constants$0.const$3.varHandle(MemoryLayout.PathElement.groupElement("__wch"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_LONG.withName("__pos"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("__count"),
            MemoryLayout.unionLayout(
                JAVA_INT.withName("__wch"),
                MemoryLayout.sequenceLayout(4, JAVA_BYTE).withName("__wchb")
            ).withName("__value")
        ).withName("__state")
    ).withName("_G_fpos_t");
}


