// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "fscanf",
        constants$9.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandleVariadic(
        "scanf",
        constants$7.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "sscanf",
        constants$9.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "vfscanf",
        constants$14.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vscanf",
        constants$9.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vsscanf",
        constants$14.const$5
    );
}


