// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$114 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$114() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "has_mouse_sp",
        constants$42.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getmouse_sp",
        constants$9.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ungetmouse_sp",
        constants$9.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mousemask_sp",
        constants$69.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mouseinterval_sp",
        constants$27.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mcprint",
        constants$27.const$2
    );
}


