// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$103 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$103() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "start_color_sp",
        constants$7.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "termattrs_sp",
        constants$7.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "termname_sp",
        constants$10.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "typeahead_sp",
        constants$27.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ungetch_sp",
        constants$27.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "use_env_sp",
        constants$39.const$0
    );
}


