// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$53 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$53() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mvwinstr",
        constants$49.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandleVariadic(
        "mvwprintw",
        constants$49.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "mvwscanw",
        constants$49.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mvwvline",
        constants$51.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "napms",
        constants$19.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "newpad",
        constants$53.const$5
    );
}


