// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$61 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$61() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "slk_attroff",
        constants$19.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "slk_attr_off",
        constants$16.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "slk_attron",
        constants$19.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "slk_attr_on",
        constants$16.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "slk_attrset",
        constants$19.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "slk_attr",
        constants$18.const$2
    );
}


