// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fseeko",
        constants$23.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ftello",
        constants$23.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "fgetpos",
        constants$9.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fsetpos",
        constants$9.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "clearerr",
        constants$14.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "feof",
        constants$7.const$2
    );
}


