// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$35 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$35() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "deleteln",
        constants$18.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "derwin",
        constants$35.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "doupdate",
        constants$18.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "dupwin",
        constants$10.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "echo",
        constants$18.const$2
    );
}


