// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$90 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$90() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "wgetscrreg",
        constants$14.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(NCURSES_OUTC_sp.class, "apply", constants$27.const$2);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "new_prescr",
        constants$10.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "baudrate_sp",
        constants$7.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "beep_sp",
        constants$7.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "can_change_color_sp",
        constants$42.const$5
    );
}


