// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final VarHandle const$0 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_fileno"));
    static final VarHandle const$1 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_flags2"));
    static final VarHandle const$2 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_old_offset"));
    static final VarHandle const$3 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_cur_column"));
    static final VarHandle const$4 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_vtable_offset"));
    static final VarHandle const$5 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("_lock"));
}


