// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$52 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$52() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mvwinchnstr",
        constants$49.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mvwinchstr",
        constants$49.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mvwinnstr",
        constants$49.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mvwinsch",
        constants$49.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mvwinsnstr",
        constants$49.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mvwinsstr",
        constants$49.const$5
    );
}


