// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$113 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$113() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "wenclose",
        constants$107.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mouseinterval",
        constants$19.const$3
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "wmouse_trafo",
        constants$113.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mouse_trafo",
        constants$113.const$4
    );
}


