// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$58 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$58() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "refresh",
        constants$18.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "resetty",
        constants$18.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "reset_prog_mode",
        constants$18.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "reset_shell_mode",
        constants$18.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(ripoffline$x0.class, "apply", constants$27.const$2);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$27.const$2
    );
}


