// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$78 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$78() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "wvline",
        constants$31.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "tigetflag",
        constants$7.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "tigetnum",
        constants$7.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "tigetstr",
        constants$10.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "putp",
        constants$7.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandleVariadic(
        "tparm",
        constants$10.const$3
    );
}


