// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*cookie_seek_function_t)(void* __cookie,long* __pos,int __w);
 * }
 */
public interface cookie_seek_function_t {

    int apply(java.lang.foreign.MemorySegment __cookie, java.lang.foreign.MemorySegment __pos, int __w);
    static MemorySegment allocate(cookie_seek_function_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$7.const$0, fi, constants$6.const$5, scope);
    }
    static cookie_seek_function_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment ___cookie, java.lang.foreign.MemorySegment ___pos, int ___w) -> {
            try {
                return (int)constants$7.const$1.invokeExact(symbol, ___cookie, ___pos, ___w);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


