// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     short id;
 *     int x;
 *     int y;
 *     int z;
 *     mmask_t bstate;
 * };
 * }
 */
public class MEVENT {

    public static MemoryLayout $LAYOUT() {
        return constants$111.const$2;
    }
    public static VarHandle id$VH() {
        return constants$111.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * short id;
     * }
     */
    public static short id$get(MemorySegment seg) {
        return (short)constants$111.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * short id;
     * }
     */
    public static void id$set(MemorySegment seg, short x) {
        constants$111.const$3.set(seg, x);
    }
    public static short id$get(MemorySegment seg, long index) {
        return (short)constants$111.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void id$set(MemorySegment seg, long index, short x) {
        constants$111.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle x$VH() {
        return constants$111.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int x;
     * }
     */
    public static int x$get(MemorySegment seg) {
        return (int)constants$111.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int x;
     * }
     */
    public static void x$set(MemorySegment seg, int x) {
        constants$111.const$4.set(seg, x);
    }
    public static int x$get(MemorySegment seg, long index) {
        return (int)constants$111.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void x$set(MemorySegment seg, long index, int x) {
        constants$111.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle y$VH() {
        return constants$111.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int y;
     * }
     */
    public static int y$get(MemorySegment seg) {
        return (int)constants$111.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int y;
     * }
     */
    public static void y$set(MemorySegment seg, int x) {
        constants$111.const$5.set(seg, x);
    }
    public static int y$get(MemorySegment seg, long index) {
        return (int)constants$111.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void y$set(MemorySegment seg, long index, int x) {
        constants$111.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle z$VH() {
        return constants$112.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int z;
     * }
     */
    public static int z$get(MemorySegment seg) {
        return (int)constants$112.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int z;
     * }
     */
    public static void z$set(MemorySegment seg, int x) {
        constants$112.const$0.set(seg, x);
    }
    public static int z$get(MemorySegment seg, long index) {
        return (int)constants$112.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void z$set(MemorySegment seg, long index, int x) {
        constants$112.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle bstate$VH() {
        return constants$112.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * mmask_t bstate;
     * }
     */
    public static int bstate$get(MemorySegment seg) {
        return (int)constants$112.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * mmask_t bstate;
     * }
     */
    public static void bstate$set(MemorySegment seg, int x) {
        constants$112.const$1.set(seg, x);
    }
    public static int bstate$get(MemorySegment seg, long index) {
        return (int)constants$112.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void bstate$set(MemorySegment seg, long index, int x) {
        constants$112.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


