// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class NCurses_1 {

    /**
     * {@snippet :
     * #define A_COLOR 65280
     * }
     */
    public static int A_COLOR() {
        return (int)65280L;
    }
    /**
     * {@snippet :
     * #define A_STANDOUT 65536
     * }
     */
    public static int A_STANDOUT() {
        return (int)65536L;
    }
    /**
     * {@snippet :
     * #define A_UNDERLINE 131072
     * }
     */
    public static int A_UNDERLINE() {
        return (int)131072L;
    }
    /**
     * {@snippet :
     * #define A_REVERSE 262144
     * }
     */
    public static int A_REVERSE() {
        return (int)262144L;
    }
    /**
     * {@snippet :
     * #define A_BLINK 524288
     * }
     */
    public static int A_BLINK() {
        return (int)524288L;
    }
    /**
     * {@snippet :
     * #define A_DIM 1048576
     * }
     */
    public static int A_DIM() {
        return (int)1048576L;
    }
    /**
     * {@snippet :
     * #define A_BOLD 2097152
     * }
     */
    public static int A_BOLD() {
        return (int)2097152L;
    }
    /**
     * {@snippet :
     * #define A_ALTCHARSET 4194304
     * }
     */
    public static int A_ALTCHARSET() {
        return (int)4194304L;
    }
    /**
     * {@snippet :
     * #define A_INVIS 8388608
     * }
     */
    public static int A_INVIS() {
        return (int)8388608L;
    }
    /**
     * {@snippet :
     * #define A_PROTECT 16777216
     * }
     */
    public static int A_PROTECT() {
        return (int)16777216L;
    }
    /**
     * {@snippet :
     * #define A_HORIZONTAL 33554432
     * }
     */
    public static int A_HORIZONTAL() {
        return (int)33554432L;
    }
    /**
     * {@snippet :
     * #define A_LEFT 67108864
     * }
     */
    public static int A_LEFT() {
        return (int)67108864L;
    }
    /**
     * {@snippet :
     * #define A_LOW 134217728
     * }
     */
    public static int A_LOW() {
        return (int)134217728L;
    }
    /**
     * {@snippet :
     * #define A_RIGHT 268435456
     * }
     */
    public static int A_RIGHT() {
        return (int)268435456L;
    }
    /**
     * {@snippet :
     * #define A_TOP 536870912
     * }
     */
    public static int A_TOP() {
        return (int)536870912L;
    }
    /**
     * {@snippet :
     * #define A_VERTICAL 1073741824
     * }
     */
    public static int A_VERTICAL() {
        return (int)1073741824L;
    }
    /**
     * {@snippet :
     * #define A_ITALIC 2147483648
     * }
     */
    public static int A_ITALIC() {
        return (int)2147483648L;
    }
    /**
     * {@snippet :
     * #define NCURSES_BUTTON_RELEASED 1
     * }
     */
    public static long NCURSES_BUTTON_RELEASED() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define NCURSES_BUTTON_PRESSED 2
     * }
     */
    public static long NCURSES_BUTTON_PRESSED() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define NCURSES_BUTTON_CLICKED 4
     * }
     */
    public static long NCURSES_BUTTON_CLICKED() {
        return 4L;
    }
    /**
     * {@snippet :
     * #define NCURSES_DOUBLE_CLICKED 8
     * }
     */
    public static long NCURSES_DOUBLE_CLICKED() {
        return 8L;
    }
    /**
     * {@snippet :
     * #define NCURSES_TRIPLE_CLICKED 16
     * }
     */
    public static long NCURSES_TRIPLE_CLICKED() {
        return 16L;
    }
    /**
     * {@snippet :
     * #define NCURSES_RESERVED_EVENT 32
     * }
     */
    public static long NCURSES_RESERVED_EVENT() {
        return 32L;
    }
    /**
     * {@snippet :
     * #define BUTTON1_RELEASED 1
     * }
     */
    public static long BUTTON1_RELEASED() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define BUTTON1_PRESSED 2
     * }
     */
    public static long BUTTON1_PRESSED() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define BUTTON1_CLICKED 4
     * }
     */
    public static long BUTTON1_CLICKED() {
        return 4L;
    }
    /**
     * {@snippet :
     * #define BUTTON1_DOUBLE_CLICKED 8
     * }
     */
    public static long BUTTON1_DOUBLE_CLICKED() {
        return 8L;
    }
    /**
     * {@snippet :
     * #define BUTTON1_TRIPLE_CLICKED 16
     * }
     */
    public static long BUTTON1_TRIPLE_CLICKED() {
        return 16L;
    }
    /**
     * {@snippet :
     * #define BUTTON2_RELEASED 32
     * }
     */
    public static long BUTTON2_RELEASED() {
        return 32L;
    }
    /**
     * {@snippet :
     * #define BUTTON2_PRESSED 64
     * }
     */
    public static long BUTTON2_PRESSED() {
        return 64L;
    }
    /**
     * {@snippet :
     * #define BUTTON2_CLICKED 128
     * }
     */
    public static long BUTTON2_CLICKED() {
        return 128L;
    }
    /**
     * {@snippet :
     * #define BUTTON2_DOUBLE_CLICKED 256
     * }
     */
    public static long BUTTON2_DOUBLE_CLICKED() {
        return 256L;
    }
    /**
     * {@snippet :
     * #define BUTTON2_TRIPLE_CLICKED 512
     * }
     */
    public static long BUTTON2_TRIPLE_CLICKED() {
        return 512L;
    }
    /**
     * {@snippet :
     * #define BUTTON3_RELEASED 1024
     * }
     */
    public static long BUTTON3_RELEASED() {
        return 1024L;
    }
    /**
     * {@snippet :
     * #define BUTTON3_PRESSED 2048
     * }
     */
    public static long BUTTON3_PRESSED() {
        return 2048L;
    }
    /**
     * {@snippet :
     * #define BUTTON3_CLICKED 4096
     * }
     */
    public static long BUTTON3_CLICKED() {
        return 4096L;
    }
    /**
     * {@snippet :
     * #define BUTTON3_DOUBLE_CLICKED 8192
     * }
     */
    public static long BUTTON3_DOUBLE_CLICKED() {
        return 8192L;
    }
    /**
     * {@snippet :
     * #define BUTTON3_TRIPLE_CLICKED 16384
     * }
     */
    public static long BUTTON3_TRIPLE_CLICKED() {
        return 16384L;
    }
    /**
     * {@snippet :
     * #define BUTTON4_RELEASED 32768
     * }
     */
    public static long BUTTON4_RELEASED() {
        return 32768L;
    }
    /**
     * {@snippet :
     * #define BUTTON4_PRESSED 65536
     * }
     */
    public static long BUTTON4_PRESSED() {
        return 65536L;
    }
    /**
     * {@snippet :
     * #define BUTTON4_CLICKED 131072
     * }
     */
    public static long BUTTON4_CLICKED() {
        return 131072L;
    }
    /**
     * {@snippet :
     * #define BUTTON4_DOUBLE_CLICKED 262144
     * }
     */
    public static long BUTTON4_DOUBLE_CLICKED() {
        return 262144L;
    }
    /**
     * {@snippet :
     * #define BUTTON4_TRIPLE_CLICKED 524288
     * }
     */
    public static long BUTTON4_TRIPLE_CLICKED() {
        return 524288L;
    }
    /**
     * {@snippet :
     * #define BUTTON5_RELEASED 1048576
     * }
     */
    public static long BUTTON5_RELEASED() {
        return 1048576L;
    }
    /**
     * {@snippet :
     * #define BUTTON5_PRESSED 2097152
     * }
     */
    public static long BUTTON5_PRESSED() {
        return 2097152L;
    }
    /**
     * {@snippet :
     * #define BUTTON5_CLICKED 4194304
     * }
     */
    public static long BUTTON5_CLICKED() {
        return 4194304L;
    }
    /**
     * {@snippet :
     * #define BUTTON5_DOUBLE_CLICKED 8388608
     * }
     */
    public static long BUTTON5_DOUBLE_CLICKED() {
        return 8388608L;
    }
    /**
     * {@snippet :
     * #define BUTTON5_TRIPLE_CLICKED 16777216
     * }
     */
    public static long BUTTON5_TRIPLE_CLICKED() {
        return 16777216L;
    }
    /**
     * {@snippet :
     * #define BUTTON_CTRL 33554432
     * }
     */
    public static long BUTTON_CTRL() {
        return 33554432L;
    }
    /**
     * {@snippet :
     * #define BUTTON_SHIFT 67108864
     * }
     */
    public static long BUTTON_SHIFT() {
        return 67108864L;
    }
    /**
     * {@snippet :
     * #define BUTTON_ALT 134217728
     * }
     */
    public static long BUTTON_ALT() {
        return 134217728L;
    }
    /**
     * {@snippet :
     * #define REPORT_MOUSE_POSITION 268435456
     * }
     */
    public static long REPORT_MOUSE_POSITION() {
        return 268435456L;
    }
    /**
     * {@snippet :
     * #define ALL_MOUSE_EVENTS 268435455
     * }
     */
    public static long ALL_MOUSE_EVENTS() {
        return 268435455L;
    }
    /**
     * {@snippet :
     * #define TRACE_MAXIMUM 8191
     * }
     */
    public static int TRACE_MAXIMUM() {
        return (int)8191L;
    }
}


