// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*NCURSES_OUTC_sp)(struct screen*,int);
 * }
 */
public interface NCURSES_OUTC_sp {

    int apply(java.lang.foreign.MemorySegment _x0, int _x1);
    static MemorySegment allocate(NCURSES_OUTC_sp fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$90.const$1, fi, constants$27.const$2, scope);
    }
    static NCURSES_OUTC_sp ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, int __x1) -> {
            try {
                return (int)constants$58.const$5.invokeExact(symbol, __x0, __x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


