// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*NCURSES_OUTC)(int);
 * }
 */
public interface NCURSES_OUTC {

    int apply(int _x0);
    static MemorySegment allocate(NCURSES_OUTC fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$27.const$4, fi, constants$19.const$3, scope);
    }
    static NCURSES_OUTC ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int __x0) -> {
            try {
                return (int)constants$27.const$5.invokeExact(symbol, __x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


