// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*ripoffline_sp$x0)(WINDOW*,int);
 * }
 */
public interface ripoffline_sp$x0 {

    int apply(java.lang.foreign.MemorySegment _x0, int _x1);
    static MemorySegment allocate(ripoffline_sp$x0 fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$99.const$2, fi, constants$27.const$2, scope);
    }
    static ripoffline_sp$x0 ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, int __x1) -> {
            try {
                return (int)constants$58.const$5.invokeExact(symbol, __x0, __x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


