// Generated by jextract

package org.taulin.bindings.ncurses;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _win_st WINDOW;
 * }
 */
public final class WINDOW {

    // Suppresses default constructor, ensuring non-instantiability.
    private WINDOW() {}
}


